### ISSUE TITLE
I am willing to support your project. 

### ISSUE THREAD

**Issue by ztyjason** [BlackOak1337/Project-Prevail#2]
HR vision AI has both advantages and disadvantages. 
Just make good use of the advantages. 
I've discovered quite a few decks suitable for HR. 

wild

### DM priest
AAEBAea5AwSRvALHpAbfwAb8wAYN1AX7D+mwA/LJA+W2BKviBJWqBe6eBvyoBtbABtjABvbABq3FBgABA/OzBsekBvazBsekBujeBsekBgAA

### shadow-priest
AAEBAa0GApG8Arv3Aw6hBJEP6bADurYD184DrfcDhoMF3aQFyKEGxKgG/KgG17oG1cEGrcUGAAA=

The standard ladder is terrible.
It's still a bit wild and comfortable.
These 2 card sets WR70%

**Comment by akira149** [comment]
I would assume that these two WILD decks work undert the default, am I correct?

**Comment by ztyjason** [comment]
Hey buddy, do you have instant messaging?


Jason&nbsp;z
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BlackOak1337/Project-Prevail"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月2日(星期六) 晚上7:23
***@***.***&gt;;
抄送:&nbsp;"Jason ***@***.******@***.***&gt;;
主题:&nbsp;Re: [BlackOak1337/Project-Prevail] I am willing to support your project.  (Issue #2)





 
I would assume that these two WILD decks work undert the default, am I correct?
